"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import React from 'react';

import { CardViewSwitcher } from '@sitecore-search/ui';

type CardViewSwitcherProps = {
  onToggle: (value: string) => void;
  defaultCardView: 'list' | 'grid';
  GridIcon: React.FC;
  ListIcon: React.FC;
};

const CardViewSwitcherComponent = ({ onToggle, defaultCardView, GridIcon, ListIcon }: CardViewSwitcherProps) => {
  return (
    <CardViewSwitcher.Root onValueChange={onToggle} defaultValue={defaultCardView} className="inline-flex">
      <CardViewSwitcher.Item
        value="grid"
        aria-label="Grid View"
        className="mr-2 items-center rounded-md bg-avid-surface text-avid-text-muted flex h-[30px] justify-center w-[30px] ml-0 hover:bg-avid-surface-elevated data-[state=on]:bg-avid-purple data-[state=on]:text-white focus:outline-avid-purple"
      >
        <GridIcon />
      </CardViewSwitcher.Item>
      <CardViewSwitcher.Item
        value="list"
        aria-label="List View"
        className="items-center rounded-md bg-avid-surface text-avid-text-muted flex h-[30px] justify-center w-[30px] ml-0 hover:bg-avid-surface-elevated data-[state=on]:bg-avid-purple data-[state=on]:text-white focus:outline-avid-purple"
      >
        <ListIcon />
      </CardViewSwitcher.Item>
    </CardViewSwitcher.Root>
  );
};

export default CardViewSwitcherComponent;
